name: money_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  firebase_core: ^4.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  intl: ^0.20.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
